services:
  php80:
    build:
      dockerfile: 8.0/Dockerfile
      context: .docker/php
    container_name: fcc_php80
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  php81:
    build:
      dockerfile: 8.1/Dockerfile
      context: .docker/php
    container_name: fcc_php81
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  php82:
    build:
      dockerfile: 8.2/Dockerfile
      context: .docker/php
    container_name: fcc_php82
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  php83:
    build:
      dockerfile: 8.3/Dockerfile
      context: .docker/php
    container_name: fcc_php83
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  php84:
    build:
      dockerfile: 8.4/Dockerfile
      context: .docker/php
    container_name: fcc_php84
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  php85:
    build:
      dockerfile: 8.5/Dockerfile
      context: .docker/php
    container_name: fcc_php85
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  docs:
    image: node:24-alpine
    profiles: [ docs ]
    working_dir: /repo/website
    restart: "no"
    ports:
      - "3000:3000"
    volumes:
      - ./:/repo

  docs-api:
    build:
      context: .docker/docs-api
    profiles: [ docs ]
    restart: "no"
    volumes:
      - ./:/repo

networks:
  fcc_network: