import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'Contribution guide', href: '/contributing'},
    {
      type: 'category',
      label: 'Changelog',
      collapsed: true,
      items: ['4.x', '3.x', '2.x', '1.x'].map((version) => ({
        type: 'link' as const,
        label: version,
        href: `/changelog/${version}`,
      })),
    },
    {type: 'link', label: 'License', href: '/license'},
  ],
};

export default sidebars;
