import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'Contribution guide', href: '/contributing'},
    {type: 'link', label: 'License', href: '/license'},
  ],
};

export default sidebars;
