name: Compatible with Rust FastCGI server

on:
  push:
    branches:
      - master
      - development
      - '*.x-dev'

  pull_request:

  schedule:
    - cron: "13 7 * * *"

  workflow_dispatch:

jobs:
  compatibility:
    uses: ./.github/workflows/compatibility.yml
    with:
      server: rust
