name: Compatible with Java FastCGI server

on:
  push:
    branches:
      - master
      - development

  pull_request:

  schedule:
    - cron: "19 7 * * *"

  workflow_dispatch:

jobs:
  compatibility:
    uses: ./.github/workflows/compatibility.yml
    with:
      server: java
